query AllAbouts($first: IntType = 100, $skip: IntType = 0) {
	allAbouts(first: $first, skip: $skip) {
		...AboutFragment
	}
	_allAboutsMeta {
		count
	}
}

query About($slug: String!) {
	about(filter: { slug: { eq: $slug } }) {
		...AboutFragment
	}
}

fragment AboutFragment on AboutRecord {
	id
	title
	image {
		...ImageFragment
	}
	intro {
		blocks
		links
		value
	}
	slug
	contentWrapper {
		id
		content {
			__typename
			blocks {
				__typename
				... on ButtonRecord {
					id
					text
					url
				}
				... on ExpandableListRecord {
					id
					items {
						__typename
						... on ExpandableListItemRecord {
							id
							title
							text {
								blocks
								links
								value
							}
						}
					}
				}
				... on ImageRecord {
					id
					image {
						...ImageFragment
					}
				}
				... on VideoExternalRecord {
					id
					caption
					video {
						height
						width
						url
						provider
						providerUid
						title
						thumbnailUrl
					}
				}
				... on VideoInternalRecord {
					id
					file {
						...VideoFragment
					}
					caption
				}
			}
			links
			value
		}
	}
}
