query Contact {
	contact {
		...ContactFragment
	}
}

fragment ContactFragment on ContactRecord {
	id
	title
	contentWrapper {
		id
		content {
			__typename
			blocks {
				__typename
				... on ButtonRecord {
					id
					text
					url
				}
				... on ExpandableListRecord {
					id
					item {
						__typename
						... on ExpandableListItemRecord {
							id
							title
							text {
								blocks
								links
								value
							}
						}
					}
				}
				... on ImageRecord {
					id
					image {
						...ImageFragment
					}
				}
				... on VideoExternalRecord {
					id
					caption
					video {
						height
						width
						url
						provider
						providerUid
						title
						thumbnailUrl
					}
				}
				... on VideoInternalRecord {
					id
					file {
						...VideoFragment
					}
					caption
				}
			}
			links
			value
		}
	}
}
