query Home {
	home {
		id
		movieStart {
			...MediaFragment
		}
		content {
			__typename
			... on ShortcutImageRecord {
				id
				image {
					...ImageFragment
				}
				title
				text {
					blocks
					links
					value
				}
				link {
					__typename
					... on ExternalLinkRecord {
						id
						title
						url
					}
					... on InternalLinkRecord {
						id
						title
						link {
							__typename
							... on AboutRecord {
								...AboutFragment
							}
							... on ContactRecord {
								...ContactFragment
							}
							... on EducationRecord {
								...EducationFragment
							}
							... on NewsRecord {
								...NewsFragment
							}
							... on ProjectRecord {
								...ProjectFragment
							}
							... on EnglishRecord {
								...EnglishFragment
							}
							... on PressRecord {
								...PressFragment
							}
						}
					}
				}
			}
			... on ShortcutMovieRecord {
				id
				movie {
					...VideoFragment
				}
				text {
					blocks
					links
					value
				}
				link {
					__typename
					... on ExternalLinkRecord {
						id
						title
						url
					}
					... on InternalLinkRecord {
						id
						title
						link {
							__typename
							... on AboutRecord {
								...AboutFragment
							}
							... on ContactRecord {
								...ContactFragment
							}
							... on EducationRecord {
								...EducationFragment
							}
							... on NewsRecord {
								...NewsFragment
							}
							... on ProjectRecord {
								...ProjectFragment
							}
							... on EnglishRecord {
								...EnglishFragment
							}
							... on PressRecord {
								...PressFragment
							}
						}
					}
				}
			}
			... on ShortcutNewsRecord {
				id
			}
			... on ShortcutProjectRecord {
				id
			}
			... on ShortcutTextRecord {
				id
				text {
					blocks
					links
					value
				}
				link {
					__typename
					... on ExternalLinkRecord {
						id
						title
						url
					}
					... on InternalLinkRecord {
						id
						title
						link {
							__typename
							... on AboutRecord {
								...AboutFragment
							}
							... on ContactRecord {
								...ContactFragment
							}
							... on EducationRecord {
								...EducationFragment
							}
							... on NewsRecord {
								...NewsFragment
							}
							... on ProjectRecord {
								...ProjectFragment
							}
							... on EnglishRecord {
								...EnglishFragment
							}
							... on PressRecord {
								...PressFragment
							}
						}
					}
				}
			}
		}
	}
}
