query Menu($first: IntType = 100, $skip: IntType = 0) {
	allAbouts(first: $first, skip: $skip) {
		id
		slug
		title
	}
	_allAboutsMeta {
		count
	}
	allEducations(first: $first, skip: $skip) {
		id
		slug
		title
	}
	_allEducationsMeta {
		count
	}
	allProjects(first: $first, skip: $skip) {
		id
		slug
		title
	}
	_allProjectsMeta {
		count
	}
	allResearches(first: $first, skip: $skip) {
		id
		slug
		title
	}
	_allResearchesMeta {
		count
	}
}
