query AllNews($first: IntType = 100, $skip: IntType = 0) {
	allNews(first: $first, skip: $skip, orderBy: [_firstPublishedAt_DESC]) {
		...NewsFragment
	}
	_allNewsMeta {
		count
	}
}

query News($slug: String) {
	news(filter: { slug: { eq: $slug } }) {
		...NewsFragment
	}
}

fragment NewsFragment on NewsRecord {
	id
	slug
	title
	image {
		...ImageFragment
	}
	intro {
		blocks
		links
		value
	}
	_firstPublishedAt
}
