query AllPresses($first: IntType = 100, $skip: IntType = 0) {
	allPresses(first: $first, skip: $skip, orderBy: [_firstPublishedAt_DESC]) {
		...PressFragment
	}
	_allPressesMeta {
		count
	}
}

query Press($slug: String) {
	press(filter: { slug: { eq: $slug } }) {
		...PressFragment
	}
}

fragment PressFragment on PressRecord {
	id
	title
	slug
	image {
		...ImageFragment
	}
	intro {
		blocks
		links
		value
	}
	_firstPublishedAt
}
